services:
  web-api:
    image: my-test-app:latest
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:8080"
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=test_ci_db;Username=user;Password=pass
      - ConnectionStrings__Redis=cache:6379
      - ASPNETCORE_URLS=http://+:8080
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - app-network  
    depends_on:
      - db
      - cache

  db:
    image: postgres:latest
    container_name: db 
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: test_ci_db
    networks:
      - app-network  
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d test_ci_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  cache:
    image: redis:latest
    networks:
      - app-network  

networks:          
  app-network:
    driver: bridge

volumes:
  postgres_data:
